# Generated by Django 6.0.5 on 2026-05-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория бара',
                'verbose_name_plural': 'Категории бара',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KidsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-метка')),
            ],
            options={
                'verbose_name': 'Категория детского меню',
                'verbose_name_plural': 'Категории детского меню',
            },
        ),
        migrations.CreateModel(
            name='BarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_type', models.CharField(choices=[('non_alcoholic', 'Б/А напитки'), ('alcoholic', 'Алкогольные напитки'), ('cocktail_classic', 'Коктейли классические'), ('cocktail_author', 'Коктейли авторские')], default='non_alcoholic', max_length=20, verbose_name='Тип напитка')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Объём (мл)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bar/', verbose_name='Фото')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('alcohol_content', models.CharField(blank=True, max_length=50, verbose_name='Крепость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.barcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Барное меню',
                'ordering': ['category', 'bar_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KidsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='kids/', verbose_name='Фото')),
                ('age_recommendation', models.CharField(blank=True, max_length=50, verbose_name='Рекомендуемый возраст')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярное')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.kidscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо детского меню',
                'verbose_name_plural': 'Детское меню',
                'ordering': ['category', 'name'],
            },
        ),
    ]
