# Generated by Django 6.0.5 on 2026-06-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер стола')),
                ('seats', models.PositiveIntegerField(default=2, verbose_name='Мест')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Позиция X (%)')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Позиция Y (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.table', verbose_name='Стол'),
        ),
    ]
