# Generated by Django 6.0.6 on 2026-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_table_reservation_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("confirmed", "Подтверждено"),
                    ("blocked", "Заблокировано админом"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="pos_x",
            field=models.IntegerField(default=0, verbose_name="Позиция X (пикс.)"),
        ),
        migrations.AlterField(
            model_name="table",
            name="pos_y",
            field=models.IntegerField(default=0, verbose_name="Позиция Y (пикс.)"),
        ),
    ]
